# Evaluating the LangGraph + Qdrant Hybrid RAG Pipeline with DeepEval

A companion notebook to `LangGraph_Qdrant_Hybrid_Rerank.ipynb`, focused entirely on **evaluation** using the open-source [DeepEval](https://github.com/confident-ai/deepeval) library.

Covers:
- DeepEval fundamentals: `LLMTestCase`, metrics, `evaluate()`
- Rebuilding a minimal version of the RAG pipeline to generate real outputs to evaluate
- Building a small evaluation dataset (queries + ground-truth context + reference answers)
- Core **RAG metrics**: Faithfulness, Answer Relevancy, Contextual Precision, Contextual Recall, Contextual Relevancy
- **Hallucination** metric
- **LLM-as-a-judge** via `GEval` - custom, criteria-based scoring
- Aggregating results into a readable scorecard
- Notes on CI integration and regression testing

**Environment:** Google Colab
**Judge / generation LLM:** OpenAI (via API key stored in Colab Secrets) - DeepEval uses an LLM internally to score most of these metrics

---
## 1. Why RAG Evaluation Needs Its Own Toolkit

A RAG pipeline has (at least) two moving parts that can each fail independently:

1. **Retrieval** - did we fetch the right context for the query?
2. **Generation** - given that context, did the LLM produce an answer that's faithful to it and actually answers the question?

Generic "is this a good answer" scoring can't tell you *which* part broke. If the answer is wrong, was it because retrieval missed the right document, or because the LLM hallucinated despite having the right context?

**DeepEval** is an open-source evaluation framework purpose-built for LLM/RAG pipelines. It provides:
- Ready-made metrics for retrieval quality (precision/recall/relevancy of retrieved context)
- Ready-made metrics for generation quality (faithfulness to context, answer relevancy, hallucination)
- A generic **LLM-as-a-judge** metric (`GEval`) for custom, criteria-based scoring when the built-in metrics don't cover your use case
- A `pytest`-style workflow (`deepeval test run`) so RAG evaluation can live in CI, not just notebooks

### 1.1 Core DeepEval Concepts

| Concept | Description |
|---|---|
| `LLMTestCase` | A single evaluation unit: `input` (query), `actual_output` (generated answer), `retrieval_context` (chunks the RAG system retrieved), and optionally `expected_output` (reference/ground-truth answer) |
| `Metric` | A scoring function (e.g., `FaithfulnessMetric`) that takes a test case and produces a score (usually 0-1) plus a pass/fail against a threshold, and a reason |
| `evaluate()` | Runs a list of test cases against a list of metrics and prints/returns a results table |
| `GEval` | A generic metric where **you** define the evaluation criteria in plain English, and an LLM judges the output against those criteria - this is the "LLM-as-a-judge" pattern |

### 1.2 Retrieval Metrics vs Generation Metrics

DeepEval's RAG metrics split cleanly along the two failure points above:

**Retrieval-focused** (do we have the right context?)
- `ContextualPrecisionMetric` - of the retrieved chunks, how many are actually relevant, and are relevant ones ranked highly?
- `ContextualRecallMetric` - did retrieval capture everything needed to produce the expected answer?
- `ContextualRelevancyMetric` - how relevant is the retrieved context to the query overall?

**Generation-focused** (given the context, is the answer good?)
- `FaithfulnessMetric` - does the answer avoid claims that contradict or aren't supported by the retrieved context? (this is DeepEval's hallucination-vs-context check)
- `AnswerRelevancyMetric` - does the answer actually address the query (regardless of correctness against context)?
- `HallucinationMetric` - a related but distinct check: does the output contradict a provided ground-truth "context" document, useful for factuality checks outside pure RAG-context grounding

We'll compute all of these, plus a custom `GEval` judge for a criterion DeepEval doesn't ship out of the box (e.g., "is the answer appropriately concise and instructional in tone").

---
## 2. Setup & Environment

Installs:
- `deepeval` - the evaluation framework
- `langgraph`, `langchain`, `langchain-openai` - to rebuild the RAG pipeline
- `qdrant-client`, `fastembed`, `sentence-transformers` - retrieval + rerank stack (same as the main notebook)

### API Key via Google Colab Secrets

Same as the main notebook: store your key under the 🔑 **Secrets** panel as `OPENAI_API_KEY` with notebook access enabled. DeepEval uses this key to run its default GPT-4o-mini judge model for most metrics (you can swap the judge model - see section 8).

### 📦 Cell 0 — Install the dependencies

Installs `deepeval` (the evaluation framework this whole notebook is about) alongside the same LangGraph/Qdrant/embedding stack from the main notebook — needed because Section 3 below rebuilds a small copy of that RAG pipeline just to have real outputs to evaluate.

In [1]:
!pip install -q deepeval langgraph langchain langchain-openai langchain-core \
    qdrant-client fastembed sentence-transformers

  WARNING: The script wheel.exe is installed in 'C:\Users\Avado\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tabulate.exe is installed in 'C:\Users\Avado\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pyfiglet.exe is installed in 'C:\Users\Avado\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script deepeval.exe is installed in 'C:\Users\Avado\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### 🔑 Cell 1 — Load the OpenAI key from Colab Secrets

Same pattern as the main notebook: pulls the key from Colab's Secrets panel instead of hardcoding it. This key does double duty here — it powers the rebuilt pipeline's `generate` step, and it's also what DeepEval uses by default to run its own "judge" LLM (`gpt-4o-mini`) that scores every metric below.

In [2]:
# --- OpenAI API key from local environment variable ---
import os

# Reads the key directly from the environment. Set it beforehand, e.g.:
#   Windows (PowerShell): $env:OPENAI_API_KEY = "sk-..."
#   macOS/Linux:           export OPENAI_API_KEY="sk-..."
assert os.environ.get("OPENAI_API_KEY"), "OPENAI_API_KEY not found in environment - set it before running this notebook."
print("OpenAI API key found in environment ✔")

OpenAI API key found in environment ✔

### 🧰 Cell 2 — Import everything: the RAG stack, plus DeepEval's evaluation pieces

Two groups of imports: the familiar retrieval/generation stack (`QdrantClient`, `TextEmbedding`, `CrossEncoder`, `StateGraph`) to rebuild the pipeline, and DeepEval's own building blocks — `LLMTestCase` (one thing-to-grade), and a set of ready-made metrics (`FaithfulnessMetric`, `AnswerRelevancyMetric`, etc.) plus `GEval` for custom criteria. Think of `LLMTestCase` as one row on an exam, and each metric as one grading rubric applied to that row.

In [3]:
# Type hints used for defining state schemas and improving code readability.
# - TypedDict: Creates strongly-typed dictionary structures.
# - List: Represents a list of objects.
from typing import TypedDict, List

# Qdrant client for interacting with the vector database.
# - QdrantClient: Connects to the Qdrant server.
# - qmodels: Contains helper models for collections, search parameters, etc.
from qdrant_client import QdrantClient, models as qmodels

# FastEmbed provides lightweight embedding models.
# - TextEmbedding: Generates dense vector embeddings.
# - SparseTextEmbedding: Generates sparse embeddings for hybrid search.
from fastembed import TextEmbedding, SparseTextEmbedding

# CrossEncoder model used for reranking retrieved documents.
# It computes relevance scores between the query and each retrieved document.
from sentence_transformers import CrossEncoder

# ChatOpenAI provides access to OpenAI chat models through LangChain.
from langchain_openai import ChatOpenAI

# LangGraph components used to build stateful AI workflows.
# - StateGraph: Creates a graph-based workflow.
# - START: Entry point of the graph.
# - END: Exit point of the graph.
from langgraph.graph import StateGraph, START, END

# DeepEval is an evaluation framework for testing the quality
# of LLM applications and Retrieval-Augmented Generation (RAG) systems.
from deepeval import evaluate

# LLMTestCase defines the inputs, outputs, and retrieval context
# used during evaluation.
from deepeval.test_case import LLMTestCase

# Pre-built evaluation metrics available in DeepEval.
#
# - FaithfulnessMetric:
#     Checks whether the generated answer is grounded in the retrieved context.
#
# - AnswerRelevancyMetric:
#     Measures how well the answer addresses the user's question.
#
# - ContextualPrecisionMetric:
#     Evaluates whether retrieved documents are relevant and free from
#     unnecessary information.
#
# - ContextualRecallMetric:
#     Measures whether the retrieval process captured all relevant information.
#
# - ContextualRelevancyMetric:
#     Evaluates the overall usefulness and relevance of the retrieved context.
#
# - HallucinationMetric:
#     Detects whether the model generates unsupported or fabricated information.
#
# - GEval:
#     A customizable LLM-as-a-Judge evaluation framework that allows
#     user-defined evaluation criteria.
from deepeval.metrics import (
    FaithfulnessMetric,
    AnswerRelevancyMetric,
    ContextualPrecisionMetric,
    ContextualRecallMetric,
    ContextualRelevancyMetric,
    HallucinationMetric,
    GEval,
)

# Defines which fields from an LLM test case should be evaluated
# when creating custom GEval metrics.
from deepeval.test_case import LLMTestCaseParams

C:\Users\Avado\AppData\Local\Temp\ipykernel_45560\739480251.py:73: DeprecationWarning: 'LLMTestCaseParams' is deprecated and will be removed in a future release. Use 'SingleTurnParams' instead.
  from deepeval.test_case import LLMTestCaseParams

---
## 3. Rebuilding a Minimal RAG Pipeline

To evaluate a RAG pipeline, we need real outputs from it - not hand-written examples. This section rebuilds a **condensed version** of the LangGraph + Qdrant + hybrid search + rerank pipeline from the main notebook (same corpus, same models) so this notebook is self-contained. If you already have `graph` compiled from the main notebook in the same runtime, you can skip straight to Section 4 and reuse it.

### 🔤 Cell 3 — Load the same dense + sparse embedding models as the main pipeline

Sets up `BAAI/bge-small-en-v1.5` (dense, meaning-based) and `Qdrant/bm25` (sparse, keyword-based) — this is the hybrid search foundation from *Retrieval Optimization Techniques*: dense catches semantic matches, sparse catches exact terms neither alone reliably finds.

In [4]:
# Initialize the dense embedding model.
#
# This model converts text into dense numerical vectors that capture
# semantic meaning, making it suitable for similarity search.
#
# Model:
#   BAAI/bge-small-en-v1.5
# Framework:
#   FastEmbed (ONNX-based, runs locally)
dense_model = TextEmbedding(
    model_name="BAAI/bge-small-en-v1.5"
)

# Initialize the sparse embedding model.
#
# Sparse embeddings capture keyword importance similar to BM25,
# making them useful for lexical retrieval.
#
# This model will be combined with dense embeddings to perform
# Hybrid Search.
sparse_model = SparseTextEmbedding(
    model_name="Qdrant/bm25"
)

# Dimension of embeddings produced by the BGE Small model.
DENSE_DIM = 384

# EMBEDDING HELPER FUNCTIONS

def embed_dense(texts):
    """
    Generate dense embeddings for a list of text documents.

    Parameters:
        texts (List[str]):
            Input text documents.

    Returns:
        List[List[float]]:
            Dense embedding vectors represented as Python lists.
    """
    return [vector.tolist() for vector in dense_model.embed(texts)]


def embed_sparse(texts):
    """
    Generate sparse embeddings for a list of text documents.

    Parameters:
        texts (List[str]):
            Input text documents.

    Returns:
        List:
            Sparse embedding objects containing:
            - indices
            - values
    """
    return list(sparse_model.embed(texts))

# LOAD CROSS-ENCODER RERANKER

# Initialize a CrossEncoder model.
#
# Unlike embedding models, the CrossEncoder jointly processes
# both the query and document to predict a highly accurate
# semantic relevance score.
#
# It is typically used after retrieval to rerank the
# top candidate documents.
reranker = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L-6-v2"
)

# INITIALIZE THE LANGUAGE MODEL

# Create the LLM used for answer generation.
#
# Temperature = 0 makes responses deterministic,
# which is generally preferred for RAG applications.
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
)


# Confirm that all models have been initialized successfully.
print("Models loaded ✔")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

Models loaded ✔

### 🗄️ Cell 4 — Spin up a fresh, in-memory Qdrant collection

Creates a throwaway `:memory:` Qdrant instance (nothing persists after the notebook session ends) with two named vectors — `dense` and `sparse` — per point, exactly like the main pipeline's collection. This is a self-contained copy just for generating fresh evaluation data, not the same collection the main notebook writes to.

In [5]:
# Name of the Qdrant collection that will store
# documents and their corresponding embeddings.
COLLECTION_NAME = "langgraph_hybrid_eval_demo"

# Create an in-memory Qdrant instance.
#
# Using ":memory:" keeps the database in RAM, making it
# ideal for notebooks, tutorials, and experimentation.
#
# Note:
# The collection will be deleted once the Python session ends.
client = QdrantClient(":memory:")

# Create a collection capable of storing both
# dense and sparse embeddings for Hybrid Search.
client.create_collection(
    collection_name=COLLECTION_NAME,

    # Configuration for dense vector embeddings.
    vectors_config={
        "dense": qmodels.VectorParams(
            size=DENSE_DIM,                     # Dimension of dense embeddings
            distance=qmodels.Distance.COSINE    # Similarity metric for vector search
        )
    },

    # Configuration for sparse vectors used for
    # keyword-based retrieval.
    sparse_vectors_config={
        "sparse": qmodels.SparseVectorParams()
    },
)

# Confirm successful collection creation.
print(f"Collection '{COLLECTION_NAME}' created ✔")

documents = [
    {"id": 0, "text": "LangGraph is a library for building stateful, multi-actor applications with LLMs, built on top of LangChain.", "topic": "langgraph"},
    {"id": 1, "text": "A StateGraph in LangGraph defines nodes, edges, and a shared state object that flows through the graph.", "topic": "langgraph"},
    {"id": 2, "text": "Unlike LCEL chains, which are directed acyclic graphs, LangGraph supports cycles and conditional branching.", "topic": "langgraph"},
    {"id": 3, "text": "Qdrant is an open-source vector database written in Rust, optimized for high-performance similarity search.", "topic": "qdrant"},
    {"id": 4, "text": "Qdrant supports named vectors, allowing multiple embeddings (e.g., dense and sparse) to be stored per point.", "topic": "qdrant"},
    {"id": 5, "text": "Hybrid search combines dense semantic vectors with sparse lexical vectors to improve retrieval accuracy.", "topic": "hybrid_search"},
    {"id": 6, "text": "Reciprocal Rank Fusion (RRF) is a common method for merging ranked lists from multiple retrieval systems.", "topic": "hybrid_search"},
    {"id": 7, "text": "BM25 is a classic sparse retrieval algorithm based on term frequency and inverse document frequency.", "topic": "hybrid_search"},
    {"id": 8, "text": "Dense embeddings encode semantic meaning, allowing retrieval of conceptually similar text even without shared keywords.", "topic": "embeddings"},
    {"id": 9, "text": "Cross-encoder rerankers score a query-document pair jointly, producing more accurate relevance scores than bi-encoders.", "topic": "reranking"},
    {"id": 10, "text": "BAAI/bge-reranker-base is an open-source cross-encoder model commonly used for reranking retrieved passages.", "topic": "reranking"},
    {"id": 11, "text": "Reranking is typically applied to a small candidate set (e.g., top 20-50) after initial retrieval, since cross-encoders are more compute-intensive.", "topic": "reranking"},
    {"id": 12, "text": "Agentic RAG systems combine retrieval-augmented generation with agent-style decision making, such as deciding whether to retrieve at all.", "topic": "agents"},
    {"id": 13, "text": "LangGraph's checkpointing feature allows persisting graph state, enabling resumability and human-in-the-loop workflows.", "topic": "langgraph"},
    {"id": 14, "text": "Conditional edges in LangGraph route execution to different nodes based on the current state, enabling dynamic control flow.", "topic": "langgraph"},
    {"id": 15, "text": "Open-source embedding models like bge-small-en-v1.5 can run efficiently on CPU, making them practical for local development.", "topic": "embeddings"},
    {"id": 16, "text": "Vector databases like Qdrant, Weaviate, and Milvus are optimized for approximate nearest neighbor search at scale.", "topic": "qdrant"},
    {"id": 17, "text": "SPLADE is a sparse retrieval model that learns term expansions, unlike BM25 which relies purely on exact term matches.", "topic": "hybrid_search"},
]

# Extract the text content from each document.
# These texts will be converted into dense and sparse embeddings.
texts = [doc["text"] for doc in documents]

# Generate dense embeddings that capture the semantic
# meaning of each document.
dense_vectors = embed_dense(texts)

# Generate sparse embeddings that capture keyword importance
# for lexical retrieval.
sparse_vectors = embed_sparse(texts)

# Create Qdrant Point objects.
#
# Each point contains:
# - A unique document ID
# - Dense embedding
# - Sparse embedding
# - Metadata (payload)
points = [
    qmodels.PointStruct(
        id=doc["id"],

        # Store both dense and sparse vectors
        # for Hybrid Search.
        vector={
            "dense": dense_vector,

            "sparse": qmodels.SparseVector(
                indices=sparse_vector.indices.tolist(),
                values=sparse_vector.values.tolist(),
            ),
        },

        # Additional metadata stored alongside
        # each document.
        payload={
            "text": doc["text"],
            "topic": doc["topic"],
        },
    )

    for doc, dense_vector, sparse_vector in zip(
        documents,
        dense_vectors,
        sparse_vectors,
    )
]

# Insert all documents into the Qdrant collection.
#
# Upsert will:
# - Insert new documents.
# - Update existing documents if the IDs already exist.
client.upsert(
    collection_name=COLLECTION_NAME,
    points=points,
)

# Display the number of successfully stored documents.
print(f"Upserted {len(points)} points.")

Collection 'langgraph_hybrid_eval_demo' created ✔

Upserted 18 points.

### 🕸️ Cell 5 — Rebuild the whole retrieve → rerank → generate pipeline in one cell

This condenses everything from the main notebook into one place: `hybrid_search()` runs dense + sparse search and fuses them with **RRF** (positional-only fusion, no reading involved — see the *Advanced RAG Architectures* notes); `RAGState` is the shared "clipboard" LangGraph nodes read from and write to; `retrieve_node` calls hybrid search, `rerank_node` re-scores the candidates with a cross-encoder (reads query+doc *together*, unlike the bi-encoder used for the first pass), and `generate_node` builds the final prompt and calls the LLM. The last few lines wire these three nodes into a compiled `graph` — the exact same shape the main notebook builds, just recreated here so this notebook can run standalone.

In [6]:
def hybrid_search(
    query: str,
    top_k: int = 10,
    prefetch_k: int = 20,
):
    """
    Perform Hybrid Search using Reciprocal Rank Fusion (RRF).

    The retrieval process combines:
        1. Dense Search (semantic similarity)
        2. Sparse Search (keyword matching)

    Qdrant first retrieves candidate documents independently
    from both indexes and then merges the rankings using
    Reciprocal Rank Fusion (RRF).

    Parameters:
        query (str):
            User's search query.

        top_k (int):
            Number of final search results.

        prefetch_k (int):
            Number of candidate documents retrieved from
            each retrieval strategy before fusion.

    Returns:
        List[ScoredPoint]:
            Ranked search results.
    """

    # Generate dense and sparse query embeddings.
    q_vec = embed_dense([query])[0]
    q_sparse = embed_sparse([query])[0]

    # Execute Hybrid Search.
    results = client.query_points(
        collection_name=COLLECTION_NAME,

        prefetch=[
            # Dense semantic retrieval
            qmodels.Prefetch(
                query=q_vec,
                using="dense",
                limit=prefetch_k,
            ),

            # Sparse keyword retrieval
            qmodels.Prefetch(
                query=qmodels.SparseVector(
                    indices=q_sparse.indices.tolist(),
                    values=q_sparse.values.tolist(),
                ),
                using="sparse",
                limit=prefetch_k,
            ),
        ],

        # Merge both rankings using RRF.
        query=qmodels.FusionQuery(
            fusion=qmodels.Fusion.RRF
        ),

        # Return the final top-k results.
        limit=top_k,
    )

    return results.points

# DEFINE LANGGRAPH STATE

class RAGState(TypedDict):
    """
    Shared state passed between all nodes in the LangGraph workflow.
    """

    # User's question.
    query: str

    # Documents retrieved from Hybrid Search.
    retrieved_docs: List[dict]

    # Top-ranked documents after CrossEncoder reranking.
    reranked_docs: List[dict]

    # Final LLM-generated answer.
    answer: str

# NODE 1: RETRIEVE DOCUMENTS

def retrieve_node(state: RAGState) -> dict:
    """
    Retrieve relevant documents using Hybrid Search.
    """

    results = hybrid_search(
        state["query"],
        top_k=10,
    )

    docs = [
        {
            "text": result.payload["text"],
            "topic": result.payload["topic"],
            "score": result.score,
        }
        for result in results
    ]

    return {
        "retrieved_docs": docs
    }

# NODE 2: RERANK DOCUMENTS

def rerank_node(state: RAGState) -> dict:
    """
    Improve document ranking using a CrossEncoder model.
    """

    # Create query-document pairs.
    pairs = [
        (state["query"], doc["text"])
        for doc in state["retrieved_docs"]
    ]

    # Compute semantic relevance scores.
    scores = reranker.predict(pairs)

    # Sort by descending relevance.
    combined = sorted(
        zip(state["retrieved_docs"], scores),
        key=lambda item: item[1],
        reverse=True,
    )

    # Keep the three most relevant documents.
    top_docs = [
        {
            **doc,
            "rerank_score": float(score),
        }
        for doc, score in combined[:3]
    ]

    return {
        "reranked_docs": top_docs
    }

# NODE 3: GENERATE ANSWER

def generate_node(state: RAGState) -> dict:
    """
    Generate the final answer using the reranked documents
    as retrieval context.
    """

    # Build the retrieval context.
    context = "\n".join(
        f"- {doc['text']}"
        for doc in state["reranked_docs"]
    )

    # Construct the RAG prompt.
    prompt = (
        "Answer the question using only the context below. "
        "If the context is insufficient, say so.\n\n"
        f"Context:\n{context}\n\n"
        f"Question: {state['query']}\n\n"
        "Answer:"
    )

    # Generate the response.
    response = llm.invoke(prompt)

    return {
        "answer": response.content
    }

# BUILD THE LANGGRAPH WORKFLOW

# Create a graph using the shared workflow state.
graph_builder = StateGraph(RAGState)

# Register workflow nodes.
graph_builder.add_node("retrieve", retrieve_node)
graph_builder.add_node("rerank", rerank_node)
graph_builder.add_node("generate", generate_node)

# Define execution order.
graph_builder.add_edge(START, "retrieve")
graph_builder.add_edge("retrieve", "rerank")
graph_builder.add_edge("rerank", "generate")
graph_builder.add_edge("generate", END)

# Compile the graph into an executable workflow.
graph = graph_builder.compile()

print("RAG pipeline rebuilt and compiled ✔")

RAG pipeline rebuilt and compiled ✔

---
## 4. Building an Evaluation Dataset

DeepEval's RAG metrics need, per example:
- `input` - the query
- `actual_output` - what the pipeline generated
- `retrieval_context` - the chunks the pipeline actually retrieved (used by faithfulness/relevancy metrics)
- `expected_output` - a reference/"gold" answer (needed for `ContextualRecallMetric` and useful for `GEval`)

We define a small hand-curated eval set: queries paired with reference answers. We'll run the pipeline live to get `actual_output` and `retrieval_context` for each.

### 📋 Cell 6 — Hand-write the evaluation set: questions + a reference answer

This is the human-verified **ground truth** from earlier in this session's discussion — six questions, each with an `expected_output` a person wrote and confirmed as correct. Nothing here is generated by the pipeline yet; this is the *answer key* the pipeline's real outputs get checked against.

In [7]:
eval_dataset = [
    {
        "query": "What is the difference between LangGraph and a LangChain LCEL chain?",
        "expected_output": "LCEL chains are linear, acyclic pipelines, while LangGraph supports stateful graphs with cycles and conditional branching, making it suited for agentic workflows.",
    },
    {
        "query": "How does hybrid search combine dense and sparse retrieval?",
        "expected_output": "Hybrid search runs dense (semantic) and sparse (lexical/BM25-style) retrieval separately, then merges the two ranked lists using a fusion method such as Reciprocal Rank Fusion (RRF).",
    },
    {
        "query": "What open-source model can be used for reranking retrieved documents?",
        "expected_output": "Open-source cross-encoder models like cross-encoder/ms-marco-MiniLM-L-6-v2 or BAAI/bge-reranker-base can be used to rerank retrieved documents.",
    },
    {
        "query": "Why would I use RRF fusion instead of dense search alone?",
        "expected_output": "RRF fusion combines dense and sparse retrieval results, capturing both semantic similarity and exact keyword matches, which can outperform dense-only search especially for queries with specific terms.",
    },
    {
        "query": "What is Qdrant and what makes it different from a regular database?",
        "expected_output": "Qdrant is an open-source vector database optimized for high-performance similarity search over embeddings, unlike regular databases which are optimized for exact-match or relational queries.",
    },
    {
        "query": "What programming language is Qdrant written in?",
        "expected_output": "Qdrant is written in Rust.",
    },
]

print(f"Eval dataset size: {len(eval_dataset)} examples")

Eval dataset size: 6 examples

### Running the Pipeline to Collect Outputs

For each query we run the compiled LangGraph pipeline and capture the reranked context plus the generated answer - these become the `retrieval_context` and `actual_output` for each `LLMTestCase`.

### ▶️ Cell 7 — Run the real pipeline on every question, and save what it actually produced

For each of the 6 questions, this calls `graph.invoke()` — running the real retrieve→rerank→generate pipeline — and saves the `actual_output` (what the model said) and the `retrieval_context` (the reranked chunks it was actually given). This is the critical step that makes evaluation possible: DeepEval needs *real* outputs, not hypothetical ones, to judge faithfulness and relevancy against.

In [8]:
# Store the outputs generated for each evaluation example.
#
# Each entry will contain:
# - User query
# - Expected (reference) answer
# - Actual answer generated by the RAG pipeline
# - Retrieval context used to generate the answer
results = []

# Execute the RAG pipeline for every evaluation example.
for example in eval_dataset:

    # Run the complete LangGraph workflow.
    output = graph.invoke(
        {
            "query": example["query"]
        }
    )

    # Save the information required for DeepEval metrics.
    results.append(
        {
            "query": example["query"],

            # Ground-truth/reference answer.
            "expected_output": example["expected_output"],

            # Answer generated by the RAG pipeline.
            "actual_output": output["answer"],

            # Context actually used by the LLM after reranking.
            "retrieval_context": [
                document["text"]
                for document in output["reranked_docs"]
            ],
        }
    )

# REVIEW GENERATED RESULTS

# Display the generated answer and retrieval context
# for each evaluation example before running DeepEval.
for result in results:

    print(f"\nQ: {result['query']}")
    print(f"A: {result['actual_output']}")

    # Display the number of retrieved context chunks
    # supplied to the language model.
    print(
        f"Context used: {len(result['retrieval_context'])} chunks"
    )

Q: What is the difference between LangGraph and a LangChain LCEL chain?
A: The difference between LangGraph and a LangChain LCEL chain is that LangGraph supports cycles and conditional branching, while LCEL chains are directed acyclic graphs. Additionally, LangGraph is designed for building stateful, multi-actor applications with LLMs and includes a StateGraph that defines nodes, edges, and a shared state object.
Context used: 3 chunks

Q: How does hybrid search combine dense and sparse retrieval?
A: Hybrid search combines dense semantic vectors, which capture the meaning of the content, with sparse lexical vectors, which focus on specific terms and their occurrences, to improve retrieval accuracy.
Context used: 3 chunks

Q: What open-source model can be used for reranking retrieved documents?
A: BAAI/bge-reranker-base is an open-source model that can be used for reranking retrieved documents.
Context used: 3 chunks

Q: Why would I use RRF fusion instead of dense search alone?
A: You would use RRF fusion instead of dense search alone to combine ranked lists from multiple retrieval systems, potentially improving the overall retrieval accuracy by leveraging the strengths of different systems.
Context used: 3 chunks

Q: What is Qdrant and what makes it different from a regular database?
A: Qdrant is an open-source vector database written in Rust, optimized for high-performance similarity search. It differs from a regular database in that it is specifically designed for storing and retrieving high-dimensional vectors, supporting named vectors and multiple embeddings per point, and is optimized for approximate nearest neighbor search at scale.
Context used: 3 chunks

Q: What programming language is Qdrant written in?
A: Qdrant is written in Rust.
Context used: 3 chunks

---
## 5. Constructing DeepEval Test Cases

Each result becomes an `LLMTestCase`. This is the standard unit DeepEval metrics operate on.

### 🧪 Cell 8 — Package each result into a DeepEval `LLMTestCase`

An `LLMTestCase` is DeepEval's standard unit — one bundle containing the question (`input`), what the model said (`actual_output`), the human-verified correct answer (`expected_output`), and the chunks it saw (`retrieval_context`). Every metric below reads from this same bundle; building it once here means every metric downstream can just reuse it.

In [9]:
# Convert each RAG pipeline result into a DeepEval LLMTestCase.
#
# Every test case contains:
# - User input (query)
# - Model-generated answer
# - Expected (reference) answer
# - Retrieval context supplied to the LLM
#
# These test cases will be used by DeepEval metrics to evaluate
# both retrieval quality and answer quality.
test_cases = [
    LLMTestCase(
        input=result["query"],
        actual_output=result["actual_output"],
        expected_output=result["expected_output"],
        retrieval_context=result["retrieval_context"],
    )
    for result in results
]

# =============================================================================
# VERIFY THE GENERATED TEST CASES
# =============================================================================

# Display the total number of evaluation test cases created.
print(f"Built {len(test_cases)} LLMTestCase objects.")

# Inspect the contents of the first test case
# to ensure everything has been populated correctly.
print("\nExample test case fields:")

print("input:")
print(test_cases[0].input)

print("\nactual_output:")
print(test_cases[0].actual_output[:120], "...")

print("\nretrieval_context:")
print(test_cases[0].retrieval_context)

Built 6 LLMTestCase objects.

Example test case fields:
input:
What is the difference between LangGraph and a LangChain LCEL chain?

actual_output:
The difference between LangGraph and a LangChain LCEL chain is that LangGraph supports cycles and conditional branching, ...

retrieval_context:
['Unlike LCEL chains, which are directed acyclic graphs, LangGraph supports cycles and conditional branching.', 'LangGraph is a library for building stateful, multi-actor applications with LLMs, built on top of LangChain.', 'A StateGraph in LangGraph defines nodes, edges, and a shared state object that flows through the graph.']

---
## 6. Core RAG Metrics

All metrics below use an LLM internally (defaulting to `gpt-4o-mini` unless configured otherwise) to judge the relationship between `input`, `actual_output`, `retrieval_context`, and `expected_output`. Each metric produces a `0-1` score, a pass/fail against `threshold`, and a natural-language `reason`.

### 6.1 Generation Metrics

- **`FaithfulnessMetric`** - checks whether claims in `actual_output` are supported by `retrieval_context`. Catches hallucination *relative to the retrieved context* - the most important metric for RAG-specific hallucination.
- **`AnswerRelevancyMetric`** - checks whether `actual_output` actually addresses `input`, independent of whether it's grounded in context. Catches "correct-sounding but off-topic" answers.

### 6.2 Retrieval Metrics

- **`ContextualPrecisionMetric`** - of the chunks in `retrieval_context`, are the relevant ones ranked near the top? Penalizes retrieving relevant docs but burying them under irrelevant ones (compares against `expected_output` to judge relevance).
- **`ContextualRecallMetric`** - does `retrieval_context` contain everything needed to produce `expected_output`? Catches retrieval that's too narrow.
- **`ContextualRelevancyMetric`** - how much of `retrieval_context`, overall, is relevant to `input`? Catches retrieval that's too broad/noisy.

### 6.3 Hallucination (context-independent)

- **`HallucinationMetric`** - checks `actual_output` against a provided reference `context` for factual contradiction. Distinct from `FaithfulnessMetric` in that it's typically used to check faithfulness to a *fixed ground-truth document*, not necessarily what was retrieved.

### 📐 Cell 9 — Define the five core RAG metrics

Each line creates one grading rubric with a passing `threshold` of 0.7: **Faithfulness** (does the answer stick to what was retrieved — catches hallucination), **Answer Relevancy** (does it address the actual question, independent of grounding), and three retrieval-focused ones — **Contextual Precision/Recall/Relevancy** — checking whether the *retrieved chunks themselves* were good, not just the final answer. This is the same generation-vs-retrieval split established earlier: some of these grade what was found, others grade what was said.

In [10]:
# Faithfulness Metric
#
# Measures whether the generated answer is fully supported
# by the retrieved context.
#
# A low score indicates that the model may be hallucinating
# or introducing information that was not present in the
# retrieved documents.
faithfulness = FaithfulnessMetric(
    threshold=0.7
)

# Answer Relevancy Metric
#
# Evaluates how well the generated answer addresses
# the user's question.
answer_relevancy = AnswerRelevancyMetric(
    threshold=0.7
)

# Contextual Precision Metric
#
# Measures whether the retrieved documents are relevant
# to the user's query while minimizing unnecessary context.
contextual_precision = ContextualPrecisionMetric(
    threshold=0.7
)

# Contextual Recall Metric
#
# Evaluates whether the retrieval system successfully
# retrieved all important information needed to answer
# the user's question.
contextual_recall = ContextualRecallMetric(
    threshold=0.7
)

# Contextual Relevancy Metric
#
# Measures the overall usefulness and relevance of the
# retrieved context for answering the user's query.
contextual_relevancy = ContextualRelevancyMetric(
    threshold=0.7
)

# GROUP ALL RAG METRICS

# Store all retrieval-related evaluation metrics in a list.
# These metrics will be passed to DeepEval during evaluation.
rag_metrics = [
    faithfulness,
    answer_relevancy,
    contextual_precision,
    contextual_recall,
    contextual_relevancy,
]

# Display the initialized metric names.
print(
    "RAG metrics initialized:",
    [metric.__class__.__name__ for metric in rag_metrics]
)

RAG metrics initialized: ['FaithfulnessMetric', 'AnswerRelevancyMetric', 'ContextualPrecisionMetric', 'ContextualRecallMetric', 'ContextualRelevancyMetric']

### 🏃 Cell 10 — Run all 5 metrics against all 6 test cases at once

`evaluate()` is DeepEval's batch runner — behind the scenes, for every test case it makes an LLM call per metric (the "LLM-as-judge" pattern), asking things like "is this answer supported by this context?", and prints a pass/fail scorecard with reasons.

In [11]:
# Run evaluation across all test cases and all RAG metrics
eval_results = evaluate(test_cases=test_cases, metrics=rag_metrics)

✨ You're running DeepEval's latest Faithfulness Metric! (using gpt-5.4, strict=False, async_mode=True)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-5.4, strict=False, async_mode=True)...

✨ You're running DeepEval's latest Contextual Precision Metric! (using gpt-5.4, strict=False, async_mode=True)...

✨ You're running DeepEval's latest Contextual Recall Metric! (using gpt-5.4, strict=False, async_mode=True)...

✨ You're running DeepEval's latest Contextual Relevancy Metric! (using gpt-5.4, strict=False, async_mode=True)...

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-22' coro=<_async_in_context.<locals>.run_in_context() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:60> wait_for=<Task pending
name='Task-35' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\pydantic\json_schema.py:335: RuntimeWarning:
coroutine 'Kernel.shell_main' was never awaited
  mapping[key] = getattr(self, method_name)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-35' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-36' coro=<_async_in_context.<locals>.run_in_context() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:60> wait_for=<Task pending
name='Task-50' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-50' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-92' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-93' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Python313\Lib\asyncio\futures.py:283: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def __await__(self):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-93' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-120' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-121' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Python313\Lib\asyncio\base_events.py:1052: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  async def create_connection(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-121' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-123' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-124' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-124' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-126' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-127' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-127' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-129' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-130' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-130' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-132' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-133' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-133' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-135' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-136' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-136' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-138' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-139' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-139' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-141' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-142' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-142' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-144' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-145' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-145' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-147' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-148' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-148' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-150' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-151' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-151' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-153' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-154' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-154' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-162' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-163' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\pydantic\json_schema.py:443: RuntimeWarning:
coroutine 'Kernel.shell_main' was never awaited
  def generate_inner(self, schema: CoreSchemaOrField) -> JsonSchemaValue:  # noqa: C901
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-163' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-165' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-166' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-166' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-168' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-169' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-169' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-171' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-172' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-172' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-192' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-193' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Python313\Lib\re\_parser.py:449: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  return list(dict.fromkeys(items))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-193' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-195' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-196' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-196' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-198' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-199' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-199' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-201' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-202' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-202' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-204' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-205' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-205' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-207' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-208' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-208' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-210' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-211' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-211' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-213' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-214' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-214' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-216' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-217' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-217' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-219' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-220' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-220' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-222' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-223' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-223' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-225' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-226' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-226' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-228' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-229' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-229' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-231' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-232' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-232' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-234' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-235' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-235' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-237' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-238' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-238' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-240' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-241' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-241' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-243' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-244' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-244' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-246' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-247' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-247' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-249' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-250' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-250' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-252' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-253' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-253' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-80' coro=<_async_in_context.<locals>.run_in_context() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:60> wait_for=<Task pending name='Task-86' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-86' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-87' coro=<_async_in_context.<locals>.run_in_context() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:60> wait_for=<Task pending name='Task-89' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-89' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-90' coro=<_async_in_context.<locals>.run_in_context() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:60> wait_for=<Task pending name='Task-91' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-91' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-95' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-96' coro=<_async_in_context.<locals>.run_in_context() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:60> wait_for=<Task pending name='Task-97' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-94' coro=<_async_in_context.<locals>.run_in_context() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:60> wait_for=<Task pending name='Task-95' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-97' coro=<Kernel.shell_main() running at C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:              What is the difference between LangGraph and a LangChain LCEL chain?                 │
│  │     Actual Output:      The difference between LangGraph and a LangChain LCEL chain is that LangGraph        │
│  │                         supports cycles and conditional branching, while LCEL chains are directed acyclic    │
│  │                         graphs. Additionally, LangGraph is designed for building stateful, multi-actor       │
│  │                         applications with LLMs and includes a StateGraph that defines nodes, edges, and a    │
│  │                         shared state object.                                                                 │
│  │     Expected Output:    LCEL chains are linear, acyclic pipelines, while LangGraph supports stateful         │
│  │                         graphs with cycles and conditional branching, making it suited for agentic           │
│  │                         workflows.                                                                           │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric               ┃ Score ┃ Threshold ┃ Reason                                                │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        PASS  │ Faithfulness         │ 1.00  │ 0.70      │ The score is 1.00 because there are no contradi...    │
│        PASS  │ Answer Relevancy     │ 1.00  │ 0.70      │ The score is 1.00 because the response appears ...    │
│        PASS  │ Contextual Precision │ 1.00  │ 0.70      │ The score is 1.00 because the retrieval context...    │
│        PASS  │ Contextual Recall    │ 1.00  │ 0.70      │ The score is 1.00 because sentence 1 is fully s...    │
│        FAIL  │ Contextual Relevancy │ 0.67  │ 0.70      │ The score is 0.67 because the retrieved context       │
│              │                      │       │           │ directly addresses the comparison by stating that     │
│              │                      │       │           │ "Unlike LCEL chains, which are directed acyclic       │
│              │                      │       │           │ graphs, LangGraph supports cycles and conditional     │
│              │                      │       │           │ branching" and that "LangGraph is a library for       │
│              │                      │       │           │ building stateful, multi-actor applications with      │
│              │                      │       │           │ LLMs," but it is only partially complete since        │
│              │                      │       │           │ there are no noted irrelevant statements and the      │
│              │                      │       │           │ context gives limited detail beyond "A StateGraph     │
│              │                      │       │           │ in LangGraph defines nodes, edges, and a shared       │
│              │                      │       │           │ state object."                                        │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_1                                                                                                 │
│  ├──   Input:              How does hybrid search combine dense and sparse retrieval?                           │
│  │     Actual Output:      Hybrid search combines dense semantic vectors, which capture the meaning of the      │
│  │                         content, with sparse lexical vectors, which focus on specific terms and their        │
│  │                         occurrences, to improve retrieval accuracy.                                          │
│  │     Expected Output:    Hybrid search runs dense (semantic) and sparse (lexical/BM25-style) retrieval        │
│  │                         separately, then merges the two ranked lists using a fusion method such as           │
│  │                         Reciprocal Rank Fusion (RRF).                                                        │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric               ┃ Score ┃ Threshold ┃ Reason                                                │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        PASS  │ Faithfulness         │ 1.00  │ 0.70      │ The score is 1.00 because there are no contradi...    │
│        PASS  │ Answer Relevancy     │ 1.00  │ 0.70      │ The score is 1.00 because the response appears ...    │
│        PASS  │ Contextual Precision │ 1.00  │ 0.70      │ The score is 1.00 because the relevant nodes in...    │
│        FAIL  │ Contextual Recall    │ 0.00  │ 0.70      │ The score is 0.00 because sentence 1 is not           │
│              │                      │       │           │ attributable to the nodes in retrieval context:       │
│              │                      │       │           │ node 1 only says hybrid search combines dense         │
│              │                      │       │           │ semantic and sparse lexical vectors, while nodes 2    │
│              │                      │       │           │ and 3 mention BM25 and SPLADE respectively, but       │
│              │                      │       │           │ none state that dense and sparse retrieval run        │
│              │                      │       │           │ separately, yield two ranked lists, or are merged     │
│              │                      │       │           │ with a fusion method like RRF.                        │
│        FAIL  │ Contextual Relevancy │ 0.33  │ 0.70      │ The score is 0.33 because the context includes one    │
│              │                      │       │           │ directly relevant statement — "Hybrid search          │
│              │                      │       │           │ combines dense semantic vectors with sparse lexical   │
│              │                      │       │           │ vectors to improve retrieval accuracy" — and a        │
│              │                      │       │           │ supporting detail that "BM25 is a classic sparse      │
│              │                      │       │           │ retrieval algorithm," but it is still limited since   │
│              │                      │       │           │ "it does not address how 'hybrid search combine       │
│              │                      │       │           │ dense and sparse retrieval'" beyond that brief        │
│              │                      │       │           │ mention.                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_2                                                                                                 │
│  ├──   Input:              What open-source model can be used for reranking retrieved documents?                │
│  │     Actual Output:      BAAI/bge-reranker-base is an open-source model that can be used for reranking        │
│  │                         retrieved documents.                                                                 │
│  │     Expected Output:    Open-source cross-encoder models like cross-encoder/ms-marco-MiniLM-L-6-v2 or        │
│  │                         BAAI/bge-reranker-base can be used to rerank retrieved documents.                    │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric               ┃ Score ┃ Threshold ┃ Reason                                                │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        PASS  │ Faithfulness         │ 1.00  │ 0.70      │ The score is 1.00 because there are no contradi...    │
│        PASS  │ Answer Relevancy     │ 1.00  │ 0.70      │ The score is 1.00 because the response directly...    │
│        PASS  │ Contextual Precision │ 1.00  │ 0.70      │ The score is 1.00 because the most relevant nod...    │
│        PASS  │ Contextual Recall    │ 1.00  │ 0.70      │ The score is 1.00 because sentence 1 is fully s...    │
│        FAIL  │ Contextual Relevancy │ 0.33  │ 0.70      │ The score is 0.33 because most of the context is      │
│              │                      │       │           │ off-target, focusing on reranking behavior like       │
│              │                      │       │           │ "applied to a small candidate set (e.g., top          │
│              │                      │       │           │ 20-50)" and "cross-encoders are more                  │
│              │                      │       │           │ compute-intensive," or embeddings such as             │
│              │                      │       │           │ "bge-small-en-v1.5" that "can run efficiently on      │
│              │                      │       │           │ CPU," without naming a reranking model. Only one      │
│              │                      │       │           │ statement directly answers the question:              │
│              │                      │       │           │ "BAAI/bge-reranker-base is an open-source             │
│              │                      │       │           │ cross-encoder model commonly used for reranking       │
│              │                      │       │           │ retrieved passages."                                  │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_3                                                                                                 │
│  ├──   Input:              Why would I use RRF fusion instead of dense search alone?                            │
│  │     Actual Output:      You would use RRF fusion instead of dense search alone to combine ranked lists       │
│  │                         from multiple retrieval systems, potentially improving the overall retrieval         │
│  │                         accuracy by leveraging the strengths of different systems.                           │
│  │     Expected Output:    RRF fusion combines dense and sparse retrieval results, capturing both semantic      │
│  │                         similarity and exact keyword matches, which can outperform dense-only search         │
│  │                         especially for queries with specific terms.                                          │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric               ┃ Score ┃ Threshold ┃ Reason                                                │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        PASS  │ Faithfulness         │ 1.00  │ 0.70      │ The score is 1.00 because there are no contradi...    │
│        PASS  │ Answer Relevancy     │ 1.00  │ 0.70      │ The score is 1.00 because the response appears ...    │
│        FAIL  │ Contextual Precision │ 0.58  │ 0.70      │ The score is 0.58 because the first node in the       │
│              │                      │       │           │ retrieval contexts is irrelevant and only says        │
│              │                      │       │           │ 'Reciprocal Rank Fusion (RRF) is a common method      │
│              │                      │       │           │ for merging ranked lists from multiple retrieval      │
│              │                      │       │           │ systems,' so it should be ranked below the second     │
│              │                      │       │           │ node, which directly explains that 'Hybrid search     │
│              │                      │       │           │ combines dense semantic vectors with sparse lexical   │
│              │                      │       │           │ vectors to improve retrieval accuracy,' and below     │
│              │                      │       │           │ the third node, which adds that 'Dense embeddings     │
│              │                      │       │           │ encode semantic meaning, allowing retrieval of        │
│              │                      │       │           │ conceptually similar text even without shared         │
│              │                      │       │           │ keywords.' The score is not lower because nodes 2     │
│              │                      │       │           │ and 3 are still relevant and together help explain    │
│              │                      │       │           │ why fusion can outperform dense search alone.         │
│        FAIL  │ Contextual Recall    │ 0.00  │ 0.70      │ The score is 0.00 because sentence 1 is not fully     │
│              │                      │       │           │ attributable to the nodes in retrieval context:       │
│              │                      │       │           │ node 1 supports that RRF merges ranked lists, and     │
│              │                      │       │           │ nodes 2–3 support combining dense and sparse          │
│              │                      │       │           │ retrieval with semantic meaning, but the context      │
│              │                      │       │           │ does not explicitly support exact keyword matches     │
│              │                      │       │           │ or the claim that this can outperform dense-only      │
│              │                      │       │           │ search, especially for queries with specific terms.   │
│        PASS  │ Contextual Relevancy │ 1.00  │ 0.70      │ The score is 1.00 because the context directly ...    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_4 (Passed 5 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_5                                                                                                 │
│  ├──   Input:              What programming language is Qdrant written in?                                      │
│  │     Actual Output:      Qdrant is written in Rust.                                                           │
│  │     Expected Output:    Qdrant is written in Rust.                                                           │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric               ┃ Score ┃ Threshold ┃ Reason                                                │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        PASS  │ Faithfulness         │ 1.00  │ 0.70      │ The score is 1.00 because there are no contradi...    │
│        PASS  │ Answer Relevancy     │ 1.00  │ 0.70      │ The score is 1.00 because the response directly...    │
│        PASS  │ Contextual Precision │ 1.00  │ 0.70      │ The score is 1.00 because the first node in the...    │
│        PASS  │ Contextual Recall    │ 1.00  │ 0.70      │ The score is 1.00 because sentence 1 is fully s...    │
│        FAIL  │ Contextual Relevancy │ 0.00  │ 0.70      │ The score is 0.00 because the cited irrelevant        │
│              │                      │       │           │ context focuses on features and use cases—"Qdrant     │
│              │                      │       │           │ supports named vectors" and "Vector databases like    │
│              │                      │       │           │ Qdrant... are optimized for approximate nearest       │
│              │                      │       │           │ neighbor search at scale"—rather than the asked       │
│              │                      │       │           │ fact. The only directly relevant statement is         │
│              │                      │       │           │ "Qdrant is an open-source vector database written     │
│              │                      │       │           │ in Rust," which answers the input.                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                         ┃ Average Score        ┃ Pass Rate                                   ┃ Total    │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━ │
│  Faithfulness                   │ 1.00                 │ 100.00% | passed=6 | failed=0               │ 6        │
│  Answer Relevancy               │ 1.00                 │ 100.00% | passed=6 | failed=0               │ 6        │
│  Contextual Precision           │ 0.90                 │ 83.33% | passed=5 | failed=1                │ 6        │

⚠ WARNING: No hyperparameters logged.
» ]8;id=327172;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 6.47s | token cost: 0.20446000000000003 USD)
» Test Results (6 total tests):
   » Pass Rate: 16.67% | Passed: 1 | Failed: 5

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

### Inspecting a Single Metric in Detail

Running a metric directly (rather than through `evaluate()`) gives access to `.score` and `.reason` for a single test case - useful when debugging why a specific example scored low.

### 🔍 Cell 11 — Zoom into one specific test case's score and reasoning

Running `faithfulness.measure(sample_case)` directly (instead of through `evaluate()`) exposes `.score` (the 0-1 number) and `.reason` (the judge LLM's own explanation for that score) for just one question — useful for debugging *why* a particular answer scored low, rather than just seeing a pass/fail table.

In [12]:
# Select one evaluation example from the dataset.
#
# This sample is used to inspect individual metric scores
# before evaluating the entire dataset.
#
# Example:
# "How does hybrid search combine dense and sparse retrieval?"
sample_case = test_cases[1]

# FAITHFULNESS EVALUATION

# Measure whether the generated answer is fully grounded
# in the retrieved context.
#
# A high score indicates that the answer does not introduce
# unsupported or hallucinated information.
faithfulness.measure(sample_case)

print("Faithfulness score:", faithfulness.score)
print("Reason:", faithfulness.reason)

# CONTEXTUAL RECALL EVALUATION

# Measure whether the retrieved documents contain
# all the information necessary to answer the query.
#
# A high score indicates that the retrieval system
# successfully captured the important context.
contextual_recall.measure(sample_case)

print("\nContextual Recall score:", contextual_recall.score)
print("Reason:", contextual_recall.reason)

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Contextual Recall score: 0.0
Reason: The score is 0.00 because sentence 1 is not supported by the nodes in retrieval context: node 1 only says hybrid search combines dense semantic vectors with sparse lexical vectors, and node 2 identifies BM25 as sparse, but neither node states that dense and sparse retrieval are run separately, that two ranked lists are merged, or that fusion methods such as RRF are used.

---
## 7. LLM-as-a-Judge with `GEval`

The built-in metrics above cover faithfulness/relevancy/recall/precision well, but sometimes you need to score something more specific to your use case - tone, instructional clarity, conciseness, whether an answer correctly cites which topic it came from, etc. `GEval` lets you define **custom evaluation criteria in plain English**; DeepEval turns that into an LLM-judged rubric (using chain-of-thought scoring internally) without you having to write a custom metric class.

Below we define two custom judges relevant to this notebook's "teaching assistant" style RAG use case:

1. **Correctness** - does the answer align with the expected/reference answer factually (a more holistic, free-form correctness check than exact match)
2. **Instructional clarity** - is the answer written clearly and concisely enough to be useful in a teaching context, avoiding unnecessary hedging or verbosity

### ⚖️ Cell 12 — Build two custom judges with `GEval`, in plain English

The five metrics above cover generic RAG quality, but sometimes you care about something specific to *your* use case. `GEval` lets you write a grading rubric in a plain-English sentence — no custom code — and DeepEval turns it into an LLM-judged score. Here: a **Correctness** judge (does the answer match the reference facts, wording aside) and an **Instructional Clarity** judge (is it well-explained for a learner). This is the same LLM-as-judge idea from earlier, just aimed at a criterion *you* define instead of a built-in one.

In [13]:
# DEFINE CUSTOM LLM-AS-A-JUDGE METRICS

# DeepEval's GEval metric allows us to create custom evaluation
# criteria using an LLM as the evaluator.
#
# Unlike the built-in RAG metrics, GEval enables us to assess
# aspects such as correctness, clarity, style, completeness,
# or any custom quality dimension.

# CORRECTNESS METRIC

# Evaluate whether the generated answer is factually consistent
# with the expected (reference) answer.
#
# The wording does not need to be identical, but the generated
# response should:
# - Preserve the important facts.
# - Avoid contradictions.
# - Avoid omitting key information.
correctness_judge = GEval(
    name="Correctness",

    criteria=(
        "Determine whether the actual output is factually consistent "
        "with the expected output. The actual output does not need "
        "to match wording, but should not contradict or omit key "
        "facts present in the expected output."
    ),

    # Fields from the test case that will be supplied
    # to the evaluation model.
    evaluation_params=[
        LLMTestCaseParams.INPUT,
        LLMTestCaseParams.ACTUAL_OUTPUT,
        LLMTestCaseParams.EXPECTED_OUTPUT,
    ],

    # Minimum passing score.
    threshold=0.7,
)

# INSTRUCTIONAL CLARITY METRIC

# Evaluate whether the generated answer is easy to understand
# for someone learning the topic.
#
# The answer should be:
# - Clear
# - Concise
# - Well-structured
# - Free from unnecessary repetition or filler
clarity_judge = GEval(
    name="Instructional Clarity",

    criteria=(
        "Evaluate whether the actual output is clear, concise, and "
        "appropriately explains the answer for someone learning the "
        "topic, without unnecessary hedging, filler, or repetition."
    ),

    evaluation_params=[
        LLMTestCaseParams.INPUT,
        LLMTestCaseParams.ACTUAL_OUTPUT,
    ],

    threshold=0.7,
)

# GROUP CUSTOM EVALUATION METRICS

# Store all custom LLM-as-a-Judge metrics in a list.
judge_metrics = [
    correctness_judge,
    clarity_judge,
]

# Display the initialized metric names.
print(
    "LLM-as-judge metrics initialized:",
    [metric.name for metric in judge_metrics],
)

LLM-as-judge metrics initialized: ['Correctness', 'Instructional Clarity']

### 🏃 Cell 13 — Run the two custom judges across all test cases

Same `evaluate()` call as Cell 10, just pointed at the custom `judge_metrics` list instead of the built-in RAG metrics — same mechanism, different rubric.

In [14]:
judge_results = evaluate(test_cases=test_cases, metrics=judge_metrics)

✨ You're running DeepEval's latest Correctness [GEval] Metric! (using gpt-5.4, strict=False, async_mode=True)...

✨ You're running DeepEval's latest Instructional Clarity [GEval] Metric! (using gpt-5.4, strict=False,
async_mode=True)...

Output()

Task was destroyed but it is pending!
task: <Task pending name='Task-482' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-483' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Python313\Lib\pathlib\_local.py:289: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  @property
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-483' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-485' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-486' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-486' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-488' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-489' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-489' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-491' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-492' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-492' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-494' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-495' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-495' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-497' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-498' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-498' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-500' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-501' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-501' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-503' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-504' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-504' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-506' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-507' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-507' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-509' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-510' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-510' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-512' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-513' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-513' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-515' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-516' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-516' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-518' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-519' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-519' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-521' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-522' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-522' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-524' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-525' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-525' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-527' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-528' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-528' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-530' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-531' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-531' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-533' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-534' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-534' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-536' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-537' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-537' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-539' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-540' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-540' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-542' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-543' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-543' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-545' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-546' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-546' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-548' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-549' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-549' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-551' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-552' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-552' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-554' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-555' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-555' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-573' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-577' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\httpcore2\_async\connection_pool.py:48:
RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def __init__(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-577' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-634' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-635' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\rich\markup.py:83: RuntimeWarning: coroutine
'Kernel.shell_main' was never awaited
  for match in RE_TAGS.finditer(markup):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-635' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-637' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-638' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-638' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-640' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-641' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-641' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-643' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-644' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-644' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-646' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-647' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-647' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-649' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-650' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-650' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-652' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-653' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-653' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-655' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-656' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-656' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-658' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-659' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-659' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-661' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-662' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-662' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-664' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-665' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-665' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-667' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-668' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-668' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-670' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-671' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-671' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-673' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-674' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\pydantic\type_adapter.py:441: RuntimeWarning:
coroutine 'Kernel.shell_main' was never awaited
  return self.validator.validate_python(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-674' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-676' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-677' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-677' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-679' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-680' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-680' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-682' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-683' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-683' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-685' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-686' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-686' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-688' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-689' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-689' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-691' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-692' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-692' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-694' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-695' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-695' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-697' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-698' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-698' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-700' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-701' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-701' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-703' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-704' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-704' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-706' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-707' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-707' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-709' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-710' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-710' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-712' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-713' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-713' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-715' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-716' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-716' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-718' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-719' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-719' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-721' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-722' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-722' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-724' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-725' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-725' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-727' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-728' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-741' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-742' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-742' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-743' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-744' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-744' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-745' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-746' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-746' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-747' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-748' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-748' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-749' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-750' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-750' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-751' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-752' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-752' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 2 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_1                                                                                                 │
│  ├──   Input:              How does hybrid search combine dense and sparse retrieval?                           │
│  │     Actual Output:      Hybrid search combines dense semantic vectors, which capture the meaning of the      │
│  │                         content, with sparse lexical vectors, which focus on specific terms and their        │
│  │                         occurrences, to improve retrieval accuracy.                                          │
│  │     Expected Output:    Hybrid search runs dense (semantic) and sparse (lexical/BM25-style) retrieval        │
│  │                         separately, then merges the two ranked lists using a fusion method such as           │
│  │                         Reciprocal Rank Fusion (RRF).                                                        │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric                        ┃ Score ┃ Threshold ┃ Reason                                       │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Correctness [GEval]           │ 0.38  │ 0.70      │ The actual output correctly mentions         │
│              │                               │       │           │ combining dense semantic vectors with        │
│              │                               │       │           │ sparse lexical signals to improve            │
│              │                               │       │           │ retrieval, which aligns with the             │
│              │                               │       │           │ high-level idea in the expected output.      │
│              │                               │       │           │ However, it omits the key mechanism          │
│              │                               │       │           │ required by the expected answer: that        │
│              │                               │       │           │ hybrid search runs dense and sparse          │
│              │                               │       │           │ retrieval separately and then merges the     │
│              │                               │       │           │ two ranked lists with a fusion method such   │
│              │                               │       │           │ as Reciprocal Rank Fusion (RRF). Because     │
│              │                               │       │           │ the Input asks how hybrid search combines    │
│              │                               │       │           │ them, leaving out separate retrieval and     │
│              │                               │       │           │ rank fusion misses essential facts.          │
│        PASS  │ Instructional Clarity [GEval] │ 0.98  │ 0.70      │ The response directly answers how hybrid     │
│              │                               │       │           │ search...                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_2 (Passed 2 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_3 (Passed 2 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_4 (Passed 2 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_5 (Passed 2 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                                 ┃ Average Score      ┃ Pass Rate                              ┃ Total   │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━ │
│  Correctness [GEval]                    │ 0.83               │ 83.33% | passed=5 | failed=1           │ 6       │
│  Instructional Clarity [GEval]          │ 0.92               │ 100.00% | passed=6 | failed=0          │ 6       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=355620;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.34s | token cost: 0.05459 USD)
» Test Results (6 total tests):
   » Pass Rate: 83.33% | Passed: 5 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

`GEval` metrics can be defined for essentially any qualitative axis you care about - e.g., "penalizes answers that don't mention the topic tag," "penalizes overly technical jargon for a beginner audience," or "rewards answers that explicitly say when context is insufficient." This is the main lever for adapting evaluation to a specific product's definition of quality, beyond generic RAG grounding checks.

---
## 8. Aggregating Results into a Scorecard

`evaluate()` prints a results table, but for a notebook it's often more useful to pull scores into a simple DataFrame to compare across examples and metrics at a glance, and to spot systematic weak points (e.g., "contextual recall is consistently the lowest metric" → suggests widening `top_k` before rerank).

### 📊 Cell 14 — Combine every metric's score into one readable table

Instead of reading through printed pass/fail blocks one at a time, this re-runs every metric (5 built-in + 2 custom) against every test case and lays the results out as a Pandas table — one row per question, one column per metric. This is what makes it easy to spot a pattern like "Contextual Recall is consistently the weakest column," which would point you back at retrieval (widen `top_k`), not generation.

In [15]:
import pandas as pd

# Combine the built-in RAG metrics with the custom
# LLM-as-a-Judge metrics into a single evaluation suite.
all_metrics = rag_metrics + judge_metrics

# Store the evaluation scores for each test case.
rows = []

# Evaluate every test case across all metrics.
for test_case in test_cases:

    # Create a row for the final scorecard.
    row = {
        "query": test_case.input
    }

    # Compute each evaluation metric.
    for metric in all_metrics:

        # Run the metric on the current test case.
        metric.measure(test_case)

        # Use the metric's custom name if available;
        # otherwise use the class name.
        metric_name = getattr(
            metric,
            "name",
            metric.__class__.__name__,
        )

        # Store the score (rounded for readability).
        row[metric_name] = (
            round(metric.score, 3)
            if metric.score is not None
            else None
        )

    # Save the completed evaluation row.
    rows.append(row)

# BUILD THE EVALUATION SCORECARD

# Convert all evaluation results into a Pandas DataFrame.
#
# Each row represents one test case.
# Each column represents one evaluation metric.
scorecard = pd.DataFrame(rows)

# Display the complete evaluation scorecard.
scorecard

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Task was destroyed but it is pending!
task: <Task pending name='Task-896' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-897' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\rich\text.py:144: RuntimeWarning: coroutine
'Kernel.shell_main' was never awaited
  def __init__(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-897' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-899' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-900' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-900' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-902' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-903' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-903' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-905' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-906' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-906' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-908' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-909' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-909' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-911' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-912' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-912' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-914' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-915' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-915' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-917' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-918' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-918' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-920' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-921' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-921' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-923' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-924' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-924' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-926' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-927' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-927' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-929' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-930' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-930' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-932' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-933' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-933' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-935' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-936' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-936' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-938' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-939' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-939' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-941' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-942' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-942' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-944' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-945' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-945' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-947' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-948' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-948' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-950' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-951' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-951' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-953' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-954' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-954' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-956' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-957' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-957' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-959' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-960' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-960' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-962' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-963' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-963' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-965' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-966' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-966' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-968' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-969' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>
Task was destroyed but it is pending!
task: <Task pending name='Task-969' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
Task was destroyed but it is pending!

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Task was destroyed but it is pending!
task: <Task pending name='Task-1143' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1144' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Python313\Lib\contextlib.py:136: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def __enter__(self):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-1144' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1146' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1147' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1147' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1149' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1150' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1150' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1152' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1153' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1153' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1155' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1156' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1156' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1158' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1159' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1159' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1161' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1162' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1162' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1164' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1165' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1165' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1167' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1168' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1168' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1170' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1171' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1171' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1173' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1174' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1174' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1176' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1177' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1177' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1179' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1180' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1180' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1182' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1183' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1183' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1185' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1186' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1186' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1188' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1189' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1189' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1191' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1192' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1192' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1194' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1195' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1195' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1197' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1198' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1198' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1200' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1201' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1201' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1203' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1204' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1204' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1206' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1207' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1207' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1209' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1210' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1210' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1212' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1213' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1213' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1215' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1216' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1216' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1218' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1219' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1219' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1221' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1222' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1222' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1224' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1225' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1225' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-1235' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1236' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Python313\Lib\traceback.py:522: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def format_frame_summary(self, frame_summary, **kwargs):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-1236' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1238' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1239' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1239' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1241' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1242' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1242' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1244' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1245' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1245' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1247' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1248' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1248' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1250' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1251' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1251' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1253' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1254' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1254' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1256' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1257' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1257' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1259' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1260' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1260' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1262' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1263' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1263' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1265' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1266' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1266' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1268' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1269' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1269' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1271' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1272' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1272' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1274' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1275' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1275' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1277' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1278' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1278' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1280' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1281' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1281' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1283' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1284' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1284' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1286' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1287' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1287' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1289' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1290' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1290' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1292' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1293' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1293' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1295' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1296' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1296' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1298' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1299' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1299' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1301' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1302' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1302' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1304' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1305' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1305' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1307' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1308' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1308' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1310' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1311' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1311' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1313' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1314' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1314' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1316' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1317' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1317' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1319' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1320' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1320' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1322' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1323' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1323' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1325' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1326' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1326' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1328' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1329' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1329' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1331' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1332' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1332' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1334' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1335' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1335' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1337' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1338' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1338' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1340' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1341' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1341' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1343' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1344' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1344' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1346' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1347' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1347' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1349' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1350' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1350' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1352' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1353' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1353' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1355' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1356' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1356' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1358' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1359' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1359' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1361' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1362' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1362' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1364' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1365' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1365' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1367' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1368' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1368' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1370' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1371' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1371' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1373' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1374' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1374' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1376' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1377' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1377' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1379' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1380' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1380' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1382' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1383' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1383' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1385' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1386' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1386' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1388' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1389' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1389' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1391' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1392' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1392' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1394' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1395' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1395' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1397' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1398' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1398' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1402' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1403' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1403' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-1408' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1409' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1409' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1411' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1412' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1412' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1414' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1415' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1415' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1417' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1418' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1418' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1420' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1421' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1421' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1423' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1424' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1424' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1426' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1427' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1427' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1429' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1430' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1430' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1432' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1433' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1433' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1435' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1436' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1436' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1438' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1439' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1439' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1441' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1442' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1442' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1444' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1445' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1445' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1447' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1448' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1448' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1450' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1451' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1451' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1453' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1454' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1454' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1456' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1457' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1457' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1459' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1460' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1460' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1462' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1463' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1463' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1465' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1466' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1466' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1468' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1469' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1469' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1471' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1472' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1472' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1474' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1475' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1475' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1477' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1478' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1478' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1480' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1481' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1481' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1483' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1484' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1484' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1486' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1487' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1487' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1489' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1490' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1490' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1492' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1493' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1493' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1495' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1496' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1496' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1498' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1499' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1499' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1501' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1502' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1502' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1504' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1505' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1505' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1507' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1508' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1508' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1510' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1511' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1511' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-1514' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1515' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Python313\Lib\json\decoder.py:361: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  obj, end = self.scan_once(s, idx)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-1515' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1517' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1518' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1518' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1520' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1521' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1521' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1523' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1524' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1524' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1526' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1527' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1527' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1529' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1530' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1530' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1532' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1533' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1533' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1535' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1536' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1536' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1538' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1539' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1539' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1541' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1542' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1542' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1544' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1545' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1545' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1547' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1548' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1548' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1550' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1551' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1551' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1553' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1554' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1554' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1556' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1557' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1557' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1559' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1560' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1560' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1562' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1563' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1563' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1565' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1566' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1566' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1568' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1569' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1569' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1571' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1572' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1572' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1574' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1575' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1575' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1577' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1578' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1578' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1580' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1581' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1581' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1583' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1584' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1584' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1586' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1587' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1587' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1589' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1590' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1590' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1592' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1593' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1593' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1595' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1596' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1596' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1598' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1599' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1599' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1601' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1602' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1602' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1604' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1605' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1605' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1607' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1608' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1608' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1610' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1611' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1611' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1613' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1614' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1614' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1616' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1617' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1617' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1619' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1620' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1620' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1622' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1623' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1623' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1625' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-1626' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-1626' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-2313' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2314' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2314' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2318' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2319' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2319' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2320' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2321' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2324' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2326' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2327' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2327' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2329' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2330' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2338' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2339' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2339' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2341' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2342' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2342' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2348' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2350' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2351' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2351' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2353' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2354' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2354' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2356' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2357' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2357' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2359' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2360' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2360' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-2879' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2880' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2880' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2882' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2883' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2883' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2885' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2886' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2886' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2888' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2889' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2889' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2891' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2892' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2892' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2894' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2895' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2895' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2897' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2898' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2898' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2900' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2901' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2901' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2903' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2904' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2904' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2906' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2907' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2907' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2909' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2910' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2910' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2912' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2913' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2913' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2915' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2916' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2916' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2918' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2919' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2919' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2921' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2922' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2922' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2924' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2925' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2925' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2927' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2928' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2928' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2930' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2931' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2931' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2933' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2934' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2934' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2936' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2937' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2937' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2939' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2940' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2940' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2942' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2943' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2943' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2945' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2946' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2946' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2948' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2949' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2949' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2951' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2952' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2966' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2967' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2967' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2971' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2972' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2972' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2973' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2974' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2974' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2976' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2977' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2977' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2979' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2980' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2980' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2982' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2983' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2983' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2985' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2986' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2986' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2988' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2989' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2989' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2991' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2992' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2992' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2994' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2995' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2995' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2997' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-2998' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-2998' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3000' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3001' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3001' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3003' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3004' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3004' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3006' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3007' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3007' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3009' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3010' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3010' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3012' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3013' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3013' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3015' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3016' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3016' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3018' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3019' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3019' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-3023' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3024' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3024' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3026' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3027' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3027' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3030' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3031' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3031' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3033' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3035' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3035' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3036' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3037' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3037' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3039' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3040' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3040' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3041' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3042' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3042' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3044' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3045' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3045' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3047' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3048' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3048' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3050' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3051' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3051' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3053' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3054' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3054' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3056' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3057' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3057' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3059' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3060' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3060' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3062' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3063' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3063' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3065' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3066' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3066' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3068' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3069' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3069' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3071' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3072' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3072' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3074' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3075' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3075' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3077' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3078' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3078' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3080' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3081' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3081' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3083' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3084' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3084' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3086' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3087' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3087' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3089' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3090' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3095' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3096' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3096' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3098' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3099' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3099' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3101' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3102' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3102' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3104' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3105' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3105' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3107' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3108' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3108' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3110' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3111' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3111' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3113' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3114' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3114' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3116' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3117' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3117' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-3122' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3124' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Python313\Lib\asyncio\base_events.py:817: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def call_soon(self, callback, *args, context=None):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-3124' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3126' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3127' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3127' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3128' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3129' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3129' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3131' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3132' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3132' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3134' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3135' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3135' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3137' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3138' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3138' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3140' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3141' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3141' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3143' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3144' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3144' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3146' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3147' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3147' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3149' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3150' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3150' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3152' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3153' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3153' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3155' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3156' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3156' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3158' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3159' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3159' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3161' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3162' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3162' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3164' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3165' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3165' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3167' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3168' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3168' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3170' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3171' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3171' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3173' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3174' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3174' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3176' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3177' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3177' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3179' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3180' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3180' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3182' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3183' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3183' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3185' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3186' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3186' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3188' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3189' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3189' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3191' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3192' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3192' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3194' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3195' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3195' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3197' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3198' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3198' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3200' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3201' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3201' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3203' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3204' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3204' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-3666' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3667' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3667' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3669' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3670' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3670' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3672' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3673' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3673' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3675' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3676' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3676' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3678' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3679' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3679' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3681' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3682' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3682' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3686' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3687' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3687' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3688' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3689' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3689' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3691' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3692' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3692' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3694' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3695' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3695' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3697' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3698' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3698' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3700' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3701' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3701' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3703' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3704' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3704' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3706' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3707' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3707' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3709' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3710' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3710' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3712' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3713' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3713' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3715' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3716' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3716' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3718' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3719' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3719' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3721' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3722' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3722' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3724' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3725' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3725' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3727' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3728' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3728' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3730' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3731' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3731' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3733' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3734' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3734' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3736' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3737' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3737' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3739' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3740' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3740' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3742' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3743' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3743' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3745' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3746' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3746' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3748' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3749' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3749' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3751' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3752' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3752' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3754' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3755' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3755' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3757' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3758' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3758' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3760' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3761' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3761' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3763' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3764' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3764' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-3768' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3769' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3769' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3770' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3771' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3771' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3773' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3774' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3774' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3776' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3777' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3777' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3779' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3780' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3780' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3782' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3783' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3783' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3785' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3786' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3786' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3788' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3789' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3789' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3791' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3792' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3792' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3794' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3795' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3795' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3797' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3798' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3798' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3800' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3801' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3801' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3803' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3804' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3804' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3806' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3807' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3807' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3809' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3810' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3810' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3812' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3813' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3813' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3815' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3816' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3816' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3818' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3819' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3819' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3821' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3822' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3822' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3824' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3825' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3825' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3827' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3828' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3828' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-3833' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3835' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\rich\markup.py:106: RuntimeWarning: coroutine
'Kernel.shell_main' was never awaited
  def render(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-3835' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3836' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3837' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3837' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3839' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3840' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3840' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3842' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3843' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3843' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3845' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3846' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3846' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3848' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3849' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3849' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3851' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3852' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3852' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3854' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3855' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3855' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3857' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3858' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3858' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3860' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3861' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3861' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3863' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3864' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3864' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3866' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3867' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3867' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3869' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3870' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3870' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3872' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3873' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3873' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3875' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3876' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3876' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3878' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3879' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3879' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3881' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3882' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3882' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3884' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3885' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3885' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3887' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3888' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3888' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3890' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3891' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3891' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3893' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3894' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3894' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3896' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3897' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3897' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3899' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3900' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3900' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3902' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3903' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3903' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3905' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3906' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3906' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3908' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3909' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3909' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3911' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3912' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3912' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3914' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3915' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3915' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3917' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3918' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3918' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3920' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-3921' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-3921' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-4389' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4390' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4390' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4392' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4393' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4393' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4395' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4396' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4396' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4398' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4399' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4399' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4401' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4402' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4402' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4428' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4429' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4429' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4431' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4432' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4432' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4434' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4435' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4435' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4437' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4438' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4438' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4440' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4441' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4441' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4443' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4444' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4444' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4446' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4447' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4447' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4449' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4450' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4450' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4453' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4454' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4454' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4456' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4457' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4457' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4459' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4460' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4460' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4462' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4463' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4463' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4465' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4466' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4466' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4468' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4469' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4469' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4471' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4472' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4472' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4474' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4475' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4475' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4477' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4478' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4478' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4480' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4481' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4481' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4483' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4484' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4484' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4486' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4487' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4487' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4489' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4490' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4490' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4492' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4493' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4493' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4495' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4496' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4496' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4498' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4499' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4499' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4501' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4502' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4502' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4504' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4505' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4505' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4507' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4508' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4508' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4510' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4511' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4511' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4513' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4514' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4514' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4516' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4517' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4517' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4519' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4520' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4520' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-4530' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4531' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4531' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4532' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4534' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4534' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4535' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4536' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4536' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4537' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4539' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4539' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4540' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4541' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4541' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4543' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4544' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4544' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4546' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4547' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4547' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4548' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4550' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4550' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4551' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4552' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4552' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4554' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4555' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4555' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4556' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4557' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4557' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4559' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4561' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4561' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4564' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4565' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4565' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4567' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4569' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4569' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4570' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4571' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4571' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4572' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4573' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4573' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4576' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4577' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4577' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4578' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4579' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4579' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4581' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4582' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4582' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4584' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4585' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4585' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4587' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4588' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4588' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4590' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4591' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4591' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4593' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4594' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4594' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4596' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4597' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4597' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4599' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4600' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4600' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4602' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4603' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4603' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4605' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4606' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4606' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4608' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4609' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4609' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4611' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4612' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4612' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4614' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4615' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4615' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4617' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4618' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4618' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4620' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4621' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4621' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4623' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4624' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4624' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4626' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4627' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4627' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4629' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4630' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4630' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4632' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4633' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4633' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4635' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4636' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4636' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-4831' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4832' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\rich\progress_bar.py:33: RuntimeWarning: coroutine
'Kernel.shell_main' was never awaited
  def __init__(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-4832' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4834' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4835' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4835' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4837' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4838' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4838' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4840' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4841' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4841' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4843' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4844' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4844' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4846' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4847' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4847' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4849' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4850' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4850' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4852' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4853' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4853' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4855' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4856' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4856' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4858' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4859' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4859' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4861' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4862' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4862' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4864' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4865' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4865' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4867' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4868' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4868' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4870' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4871' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4871' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4873' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4874' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4874' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4876' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4877' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4877' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4879' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4880' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4880' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4882' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4883' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4883' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4885' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4886' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4886' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4888' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4889' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4889' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4891' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4892' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4892' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4894' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4895' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4895' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4897' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4898' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4898' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4900' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4901' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4901' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4903' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4904' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4904' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4908' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4909' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4909' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4910' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4911' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4911' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4913' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4914' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4914' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4916' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4917' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4917' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4919' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4920' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4920' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4922' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4923' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4923' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4925' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4926' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4926' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4928' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4929' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4929' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4931' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4932' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4932' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4934' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4935' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4935' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4937' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4938' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4938' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4940' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4941' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4941' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4943' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4944' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4944' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4946' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4947' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4947' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4949' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4950' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4950' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4952' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4953' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4953' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4955' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4956' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4956' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4958' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4959' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4959' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4961' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4962' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4962' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4964' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4965' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4965' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Task was destroyed but it is pending!
task: <Task pending name='Task-4967' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4968' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4968' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4970' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4971' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4971' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4973' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4974' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4974' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4976' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4977' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4977' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4979' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4980' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4980' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4982' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4983' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4983' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4985' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4986' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4986' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4988' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4989' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4989' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4991' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4992' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4992' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4997' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-4998' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4998' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-4999' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5000' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5000' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5001' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5002' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5002' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5003' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5004' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5004' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5006' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5007' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5007' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5009' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5010' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5010' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5014' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5015' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5015' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5016' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5017' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5017' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5019' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5020' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5020' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5022' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5023' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5023' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5025' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5026' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5026' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5028' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5029' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5029' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5031' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5032' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5032' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5034' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5035' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5035' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5037' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5038' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5038' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5040' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5041' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5041' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5043' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5044' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5044' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5046' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5047' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5047' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5049' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5050' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5050' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5052' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5053' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5053' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5055' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5056' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5056' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5058' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5059' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5059' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5061' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5062' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5062' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5064' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5065' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5065' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5067' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5068' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5068' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5070' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5071' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5071' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5073' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5074' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5074' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5076' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5077' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5077' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5079' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5080' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5080' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5082' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5083' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5083' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5085' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5086' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5086' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5088' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5089' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5089' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5091' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5092' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5092' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5094' coro=<_async_in_context.<locals>.run_in_context() done, defined at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\utils.py:57> wait_for=<Task pending
name='Task-5095' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>
cb=[ZMQStream._run_callback.<locals>._log_error() at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\zmq\eventloop\zmqstream.py:564]>

Task was destroyed but it is pending!
task: <Task pending name='Task-5095' coro=<Kernel.shell_main() running at
C:\Users\Avado\AppData\Roaming\Python\Python313\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot enter context: <_contextvars.Context object at 0x000002170A6DAF40> is already entered

,query,FaithfulnessMetric,AnswerRelevancyMetric,ContextualPrecisionMetric,ContextualRecallMetric,ContextualRelevancyMetric,Correctness,Instructional Clarity
0,What is the difference between LangGraph and a...,1.0,1.0,1.000,1.0,0.667,1.000,0.992
1,How does hybrid search combine dense and spars...,1.0,1.0,1.000,0.0,0.667,0.673,1.000
2,What open-source model can be used for reranki...,1.0,1.0,1.000,1.0,0.333,0.832,1.000
3,Why would I use RRF fusion instead of dense se...,1.0,1.0,0.583,0.0,1.000,0.710,0.894
4,What is Qdrant and what makes it different fro...,1.0,1.0,0.833,1.0,0.667,1.000,0.944
5,What programming language is Qdrant written in?,1.0,1.0,1.000,1.0,0.333,1.000,1.000

### 📉 Cell 15 — Average each metric down to one number

Collapses the whole scorecard into a single ranked list — which metric is systematically weakest across all 6 questions. This is the fastest way to answer "where should I focus improvement effort first?" without eyeballing every row individually.

In [16]:
# Average score per metric - quick view of systematic strengths/weaknesses
scorecard.drop(columns=["query"]).mean().sort_values().to_frame(name="avg_score")

                           avg_score
ContextualRelevancyMetric   0.611167
ContextualRecallMetric      0.666667
Correctness                 0.869167
ContextualPrecisionMetric   0.902667
Instructional Clarity       0.971667
AnswerRelevancyMetric       1.000000
FaithfulnessMetric          1.000000

### Choosing / Configuring the Judge Model

By default, DeepEval's metrics use `gpt-4o-mini` as the judge LLM. You can point metrics at a different OpenAI model (e.g., `gpt-4o` for a stricter/more capable judge) by passing `model=` to any metric constructor:

```python
FaithfulnessMetric(threshold=0.7, model="gpt-4o")
```

For fully open-source evaluation (no OpenAI dependency even for judging), DeepEval also supports plugging in local models via its `DeepEvalBaseLLM` interface - worth exploring if you need an entirely self-hosted eval pipeline, at the cost of judge quality/consistency compared to GPT-4-class models.

---
## 9. From Notebook to CI: Regression Testing

DeepEval is designed to run inside `pytest`, which means the same metrics used here can gate pull requests or catch regressions when you change the embedder, reranker, prompt, or fusion strategy.

A minimal `pytest` version of this notebook's evaluation might look like:

```python
# test_rag_pipeline.py
import pytest
from deepeval import assert_test
from deepeval.test_case import LLMTestCase
from deepeval.metrics import FaithfulnessMetric, AnswerRelevancyMetric

@pytest.mark.parametrize("query,expected", EVAL_DATASET)
def test_rag_response(query, expected):
    out = graph.invoke({"query": query})
    test_case = LLMTestCase(
        input=query,
        actual_output=out["answer"],
        expected_output=expected,
        retrieval_context=[d["text"] for d in out["reranked_docs"]],
    )
    assert_test(test_case, [FaithfulnessMetric(threshold=0.7), AnswerRelevancyMetric(threshold=0.7)])
```

Run via `deepeval test run test_rag_pipeline.py` - this gives you pass/fail gating per metric per example, plus DeepEval's own reporting/dashboard integration if you use their hosted platform (Confident AI), which is optional.

**Practical tips for production eval sets:**
- Keep a **held-out** eval set that doesn't change when you tune prompts/retrieval - otherwise you're overfitting to your own test set
- Track metric trends over time (per model/prompt/retrieval version) rather than just pass/fail on a single run - a metric dropping from 0.91 to 0.78 average is a signal even if it's still "passing" threshold
- Pair `ContextualRecall`/`ContextualPrecision` trends with retrieval-only experiments (as in the main notebook's dense vs sparse vs hybrid comparison) to isolate whether regressions come from retrieval or generation